# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/popowi_m/Projects/laubie_g-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/popowi_m/Projects/laubie_g-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popowi_m/Projects/laubie_g-chess/CMakeFiles /home/popowi_m/Projects/laubie_g-chess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/popowi_m/Projects/laubie_g-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess

# Build rule for target.
chess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess
.PHONY : chess

# fast build rule for target.
chess/fast:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/build
.PHONY : chess/fast

src/chess-manager.o: src/chess-manager.cc.o
.PHONY : src/chess-manager.o

# target to build an object file
src/chess-manager.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/chess-manager.cc.o
.PHONY : src/chess-manager.cc.o

src/chess-manager.i: src/chess-manager.cc.i
.PHONY : src/chess-manager.i

# target to preprocess a source file
src/chess-manager.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/chess-manager.cc.i
.PHONY : src/chess-manager.cc.i

src/chess-manager.s: src/chess-manager.cc.s
.PHONY : src/chess-manager.s

# target to generate assembly for a file
src/chess-manager.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/chess-manager.cc.s
.PHONY : src/chess-manager.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/move.o: src/move.cc.o
.PHONY : src/move.o

# target to build an object file
src/move.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/move.cc.o
.PHONY : src/move.cc.o

src/move.i: src/move.cc.i
.PHONY : src/move.i

# target to preprocess a source file
src/move.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/move.cc.i
.PHONY : src/move.cc.i

src/move.s: src/move.cc.s
.PHONY : src/move.s

# target to generate assembly for a file
src/move.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/move.cc.s
.PHONY : src/move.cc.s

src/parser/option-parser.o: src/parser/option-parser.cc.o
.PHONY : src/parser/option-parser.o

# target to build an object file
src/parser/option-parser.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/option-parser.cc.o
.PHONY : src/parser/option-parser.cc.o

src/parser/option-parser.i: src/parser/option-parser.cc.i
.PHONY : src/parser/option-parser.i

# target to preprocess a source file
src/parser/option-parser.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/option-parser.cc.i
.PHONY : src/parser/option-parser.cc.i

src/parser/option-parser.s: src/parser/option-parser.cc.s
.PHONY : src/parser/option-parser.s

# target to generate assembly for a file
src/parser/option-parser.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/option-parser.cc.s
.PHONY : src/parser/option-parser.cc.s

src/parser/parserPGN.o: src/parser/parserPGN.cc.o
.PHONY : src/parser/parserPGN.o

# target to build an object file
src/parser/parserPGN.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/parserPGN.cc.o
.PHONY : src/parser/parserPGN.cc.o

src/parser/parserPGN.i: src/parser/parserPGN.cc.i
.PHONY : src/parser/parserPGN.i

# target to preprocess a source file
src/parser/parserPGN.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/parserPGN.cc.i
.PHONY : src/parser/parserPGN.cc.i

src/parser/parserPGN.s: src/parser/parserPGN.cc.s
.PHONY : src/parser/parserPGN.s

# target to generate assembly for a file
src/parser/parserPGN.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/parser/parserPGN.cc.s
.PHONY : src/parser/parserPGN.cc.s

src/player/player-pgn.o: src/player/player-pgn.cc.o
.PHONY : src/player/player-pgn.o

# target to build an object file
src/player/player-pgn.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player-pgn.cc.o
.PHONY : src/player/player-pgn.cc.o

src/player/player-pgn.i: src/player/player-pgn.cc.i
.PHONY : src/player/player-pgn.i

# target to preprocess a source file
src/player/player-pgn.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player-pgn.cc.i
.PHONY : src/player/player-pgn.cc.i

src/player/player-pgn.s: src/player/player-pgn.cc.s
.PHONY : src/player/player-pgn.s

# target to generate assembly for a file
src/player/player-pgn.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player-pgn.cc.s
.PHONY : src/player/player-pgn.cc.s

src/player/player.o: src/player/player.cc.o
.PHONY : src/player/player.o

# target to build an object file
src/player/player.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player.cc.o
.PHONY : src/player/player.cc.o

src/player/player.i: src/player/player.cc.i
.PHONY : src/player/player.i

# target to preprocess a source file
src/player/player.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player.cc.i
.PHONY : src/player/player.cc.i

src/player/player.s: src/player/player.cc.s
.PHONY : src/player/player.s

# target to generate assembly for a file
src/player/player.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/player/player.cc.s
.PHONY : src/player/player.cc.s

src/position.o: src/position.cc.o
.PHONY : src/position.o

# target to build an object file
src/position.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/position.cc.o
.PHONY : src/position.cc.o

src/position.i: src/position.cc.i
.PHONY : src/position.i

# target to preprocess a source file
src/position.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/position.cc.i
.PHONY : src/position.cc.i

src/position.s: src/position.cc.s
.PHONY : src/position.s

# target to generate assembly for a file
src/position.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/position.cc.s
.PHONY : src/position.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... chess"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/chess-manager.o"
	@echo "... src/chess-manager.i"
	@echo "... src/chess-manager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/move.o"
	@echo "... src/move.i"
	@echo "... src/move.s"
	@echo "... src/parser/option-parser.o"
	@echo "... src/parser/option-parser.i"
	@echo "... src/parser/option-parser.s"
	@echo "... src/parser/parserPGN.o"
	@echo "... src/parser/parserPGN.i"
	@echo "... src/parser/parserPGN.s"
	@echo "... src/player/player-pgn.o"
	@echo "... src/player/player-pgn.i"
	@echo "... src/player/player-pgn.s"
	@echo "... src/player/player.o"
	@echo "... src/player/player.i"
	@echo "... src/player/player.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

